name: finance

services:
  swagger:
    build: swagger-ui
    image: swagger-finance:1.0.0
    ports:
      - 81:8080
    networks:
      - finance-network
  pg_db:
    build: postgresql
    image: postgresql-finance:1.0.2
    environment:
      POSTGRES_USER: finance_admin
      POSTGRES_PASSWORD: 123
    networks:
      - finance-network

  pgadmin:
    build: pgadmin
    image: pgadmin-finance:1.0.2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@finance.com
      PGADMIN_DEFAULT_PASSWORD: finance
    ports:
      - 86:80
    networks:
      - finance-network

  user-service:
    build: user-service
    image: user-service:1.0.3
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - finance-network

  classifier-service:
    build: classifier-service
    image: classifier-service:1.0.0
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - finance-network

  account-service:
    build: account-service
    image: account-service:1.0.0
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - finance-network

  audit-service:
    build: audit-service
    image: audit-service:1.0.0
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - finance-network

  proxy:
    build: proxy
    image: proxy_finance:1.0.6
    ports:
      - 80:80
    networks:
    - finance-network


networks:
  finance-network: