server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://pg_db:5432/message
    username: message_app
    password: 123456
    driver-class-name: org.postgresql.Driver

url:
  users: http://user-service:8080/feign