
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: false
  rabbitmq:
    host: localhost
    port: 5672
    username: admin@finance.com
    password: finance

  kafka:
    bootstrap-servers: kafka:9092

redis:
  host: redis
  port: 6379

app:
  jwt:
    secret: I26tXMOZepPHyd_fDTxirlfk60dgL_P0XB8D0qhY4jI

kafka:
  topics:
    message_1: message


