server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://pg_db:5432/user
    username: user_app
    password: 123456
    driver-class-name: org.postgresql.Driver

url:
  audit: http://audit-service:8080/feign