
spring:
  datasource:
    url: jdbc:postgresql://pg_db:5432/account
    username: account_app
    password: 123456
    driver-class-name: org.postgresql.Driver

url:
  users: http://user-service:8080/feign
  classifier: http://classifier-service:8080/feign
  audit: http://audit-service:8080/feign